### ISSUE TITLE
不支持日文，韩文等文本消息

### ISSUE THREAD

**Issue by royal430** [zjiecode/wxpusher-client#1]
如果遇到这种类型的字符集，即便是UTF-8，在微信里显示也是乱码，盼望解决

**Comment by zjiecode** [comment]
主要的原因是发送到微信的时候的问题，现在微信模版被举报，已经不能直接显示，需要再次跳转。我们正在开发第二个版本，努力在第二个版本解决对特殊字符的支持，非常感谢你的反馈。

**Comment by rangerzhou** [comment]
敢问大神源码能公开吗

**Comment by rangerzhou** [comment]
看了下应该是用的微信企业号的模板消息 API 吧，回头也注册个企业号折腾一下

**Comment by zjiecode** [comment]
> 看了下应该是用的微信企业号的模板消息 API 吧，回头也注册个企业号折腾一下

使用的是认证服务号的模版消息。

**Comment by rangerzhou** [comment]
> > 看了下应该是用的微信企业号的模板消息 API 吧，回头也注册个企业号折腾一下
> 
> 使用的是认证服务号的模版消息。

群发次数：服务号1个月（按自然月）内可发送4条群发消息。
服务号的话每个月只能群发4条消息，单独发消息不受限制吗？

**Comment by rangerzhou** [comment]
> > > 看了下应该是用的微信企业号的模板消息 API 吧，回头也注册个企业号折腾一下
> > 
> > 
> > 使用的是认证服务号的模版消息。
> 
> 群发次数：服务号1个月（按自然月）内可发送4条群发消息。
> 服务号的话每个月只能群发4条消息，单独发消息不受限制吗？

看到了，日调用上限为10万次

**Comment by zjiecode** [comment]
这个问在在V2版本已经解决了。
