### ISSUE TITLE
建议回调参数增加昵称和头像

### ISSUE THREAD

**Issue by Alexander-Chiang** [zjiecode/wxpusher-client#23]
想使用该接口实现微信扫码登录，请问回调参数中能否增加用户头像和昵称信息

**Comment by zjiecode** [comment]
目前暂时不支持，但是你可以调用接口查询微信用户信息
http://wxpusher.zjiecode.com/docs/#/?id=%e6%9f%a5%e8%af%a2app%e7%9a%84%e5%85%b3%e6%b3%a8%e7%94%a8%e6%88%b7
多传递一个uid参数即可。
这个功能是才增加的，文档还没修改，你可以查看java的sdk：https://github.com/wxpusher/wxpusher-sdk-java
春节后，可以增加回调里面的信息。

**Comment by Alexander-Chiang** [comment]
很赞！

**Comment by zjiecode** [comment]
你好，已经在app关注的事件里面，增加了回调字段：
- userName 微信用户名
- userHeadImg 微信头像

其中头像字段，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像，默认是132），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效，并且暂时没有重新获取头像的机制，后面可能会考虑使用定时任务来轮训，但是用户量比较大，每天轮训一次头像也感激有点浪费资源，所以暂时没有做头像的更新。

回调的数据结构：
```
{
    "action":"app_subscribe",
    "data":{
        "appKey":"AK_xxx",
        "appName":"WxPusher演示",
        "extra":"xxxxx",
        "source":"scan",
        "time":1580286845553,
        "uid":"UID_xxxx",
        "userHeadImg":"http://thirdwx.qlogo.cn/mmopen/xxxx/132",
        "userName":"xxxx"
    }
}
```
