### ISSUE TITLE
建议将HttpUtils中的post命令中的dataStr.getBytes()更改成getBytes(StandardCharsets.UTF_8)

### ISSUE THREAD

**Issue by macoconne** [zjiecode/wxpusher-client#24]
我是个菜鸟。。。。。。。。我也不确定这个建议对不对。。。。。
我遇到了打包后发送消息请求出现了非UTF-8的问题，这个时候接口就失效了，无法正常发送命令。
必须已-Dfile.encoding=UTF-8的启动方式启动jar。

**Comment by zjiecode** [comment]
Good idea ，你可以提PR的，新的java仓库在这里：https://github.com/wxpusher/wxpusher-sdk-java

**Comment by macoconne** [comment]
好的，我尝试一下
