### ISSUE TITLE
稍微通用一点的模板消息

### ISSUE THREAD

**Issue by huxuan** [zjiecode/wxpusher-client#4]
文字消息很棒，但是毕竟有限制，需要48小时激活之类的，可以提供稍微通用一点的模板消息就好了，最好在模板卡片上可以自定义标题内容之类的。

**Comment by zjiecode** [comment]
这个之前已经尝试过，但是，会涉及到有用户投诉的问题，用户如果投诉，会导致腾讯删除模版，就导致没有办法发送消息了。
如果把模版暴露给接入的开发者，还需要开发者自己替换模版，问题太多了，所以现在做了收口，不允许替换模版，如果模版被投诉，有wxpusher统一换一个，就行了，修复起来比较快。

**Comment by huxuan** [comment]
好的，理解~之后可以看看有没有可能开放更多功能，主要现在的模板卡片本身信息量太少，必须得点进去才能看有一点点不爽，如果可能话能够开发卡片上信息的填充就更好了

**Comment by zjiecode** [comment]
现在的新版本，已经是这种效果了。
[http://wxpusher.zjiecode.com/demo/#/](http://wxpusher.zjiecode.com/demo/#/)
![image](https://user-images.githubusercontent.com/38341983/66365033-32644180-e9be-11e9-88cc-eaade63f4a6e.png)

**Comment by huxuan** [comment]
我本来希望的可能是在模板消息中，能够自定义`工单内容`甚至是标题，但是如果这样实现容易被举报的话，那就只能放弃了毕竟能用是第一要素~如果我没有理解错的话，这个issue随时可以关掉啦，还是谢谢大佬的耐心和付出！

**Comment by zjiecode** [comment]
好的，欢迎后续持续关注，现在的内信消息感觉比模版消息体验更加好。
