### ISSUE TITLE
新版接口线上调用connect reset

### ISSUE THREAD

**Issue by YeohWah** [zjiecode/wxpusher-client#6]
线上使用调用接口或直接curl 报connect reset  其他第三方接口正常

**Comment by YeohWah** [comment]
上周1.03接口突然无法发送了，切换到新的接口，新的接口本地正常到服务器就connect reset

**Comment by zjiecode** [comment]
上周是部署了新的服务器，服务负载过大导致的，目前已经添加了服务器，最近一天观察，没有问题。
再持续观察一下，应该没有问题了。

**Comment by YeohWah** [comment]
还是不行，本地机器可以，到服务器里就没法访问，包括curl都不行

**Comment by YeohWah** [comment]
今天夜里正常了
