### ISSUE TITLE
Maven仓库里还没有2.1.1版本的jar,只有2.1.0

### ISSUE THREAD

**Issue by ZhouQQQ** [zjiecode/wxpusher-client#8]
![image](https://user-images.githubusercontent.com/20562245/68640601-495cfd00-0543-11ea-8919-2e8ad372b394.png)

![image](https://user-images.githubusercontent.com/20562245/68640684-888b4e00-0543-11ea-91e8-44d6145082a8.png)

**Comment by zjiecode** [comment]
你的图片不能显示，我看了一下，maven里面是有2.1.1的。jcenter里面，没有显示，但是可以下载到。
![image](https://user-images.githubusercontent.com/38341983/69925683-5d65a000-14ec-11ea-91e9-184ccd043bce.png)
